package com.mcu.backend.apirest.models;

//Generated 02-jul-2021 15:31:59 by Hibernate Tools 4.3.1

import javax.persistence.*;
import java.util.Date;

/**
* VinPersonas generated by hbm2java
*/
@Entity
@Table(name="vin_Personas")
public class VinPersonas  implements java.io.Serializable {

 /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

@Id
 @GeneratedValue(strategy=GenerationType.IDENTITY)
 @Column(name="numero_pers")
  private Long numeroPers;
 
 @Column(name = "nombre_pers")
  private String nombrePers;
 @Column(name = "direccion_pers")
  private String direccionPers;
 @Column(name = "telefono_pers")
  private String telefonoPers;
 @Column(name = "email_pers")
  private String emailPers;
 @Column(name = "cuit_pers")
  private String cuitPers;
 @Column(name = "esclie_pers")
  private Boolean escliePers;
 @Column(name = "esprove_pers")
  private Boolean esprovePers;
 @Column(name = "fechanac_pers")
  private Date fechanacPers;
 @Column(name = "observaciones_pers")
  private String observacionesPers;
 @Column(name = "activo_pers")
  private Boolean activoPers;
 @Column(name = "codigo_pers" ,unique=true)
  private String codigoPers;
 @Column(name = "lista_pers")
  private Integer listaPers;
 @Column(name = "marca_pers")
  private String marcaPers;

 public VinPersonas() {
 }

 public VinPersonas(String nombrePers, String cuitPers) {
     this.nombrePers = nombrePers;
     this.cuitPers = cuitPers;
 }

 
 public VinPersonas(Long numeroPers) {
     this.numeroPers = numeroPers;
 }
 public VinPersonas(Long numeroPers, String nombrePers, String direccionPers, String telefonoPers, String emailPers, String cuitPers, Boolean escliePers, Boolean esprovePers, Date fechanacPers, String observacionesPers, Boolean activoPers, String codigoPers, Integer listaPers, String marcaPers) {
    this.numeroPers = numeroPers;
    this.nombrePers = nombrePers;
    this.direccionPers = direccionPers;
    this.telefonoPers = telefonoPers;
    this.emailPers = emailPers;
    this.cuitPers = cuitPers;
    this.escliePers = escliePers;
    this.esprovePers = esprovePers;
    this.fechanacPers = fechanacPers;
    this.observacionesPers = observacionesPers;
    this.activoPers = activoPers;
    this.codigoPers = codigoPers;
    this.listaPers = listaPers;
    this.marcaPers = marcaPers;
 }

 public Long getNumeroPers() {
     return this.numeroPers;
 }
 
 public void setNumeroPers(Long numeroPers) {
     this.numeroPers = numeroPers;
 }
 public String getNombrePers() {
     return this.nombrePers;
 }
 
 public void setNombrePers(String nombrePers) {
     this.nombrePers = nombrePers;
 }
 public String getDireccionPers() {
     return this.direccionPers;
 }
 
 public void setDireccionPers(String direccionPers) {
     this.direccionPers = direccionPers;
 }
 public String getTelefonoPers() {
     return this.telefonoPers;
 }
 
 public void setTelefonoPers(String telefonoPers) {
     this.telefonoPers = telefonoPers;
 }
 public String getEmailPers() {
     return this.emailPers;
 }
 
 public void setEmailPers(String emailPers) {
     this.emailPers = emailPers;
 }
 public String getCuitPers() {
     return this.cuitPers;
 }
 
 public void setCuitPers(String cuitPers) {
     this.cuitPers = cuitPers;
 }
 public Boolean getEscliePers() {
     return this.escliePers;
 }
 
 public void setEscliePers(Boolean escliePers) {
     this.escliePers = escliePers;
 }
 public Boolean getEsprovePers() {
     return this.esprovePers;
 }
 
 public void setEsprovePers(Boolean esprovePers) {
     this.esprovePers = esprovePers;
 }
 public Date getFechanacPers() {
     return this.fechanacPers;
 }
 
 public void setFechanacPers(Date fechanacPers) {
     this.fechanacPers = fechanacPers;
 }
 public String getObservacionesPers() {
     return this.observacionesPers;
 }
 
 public void setObservacionesPers(String observacionesPers) {
     this.observacionesPers = observacionesPers;
 }
 public Boolean getActivoPers() {
     return this.activoPers;
 }
 
 public void setActivoPers(Boolean activoPers) {
     this.activoPers = activoPers;
 }
 public String getCodigoPers() {
     return this.codigoPers;
 }
 
 public void setCodigoPers(String codigoPers) {
     this.codigoPers = codigoPers;
 }
 public Integer getListaPers() {
     return this.listaPers;
 }
 
 public void setListaPers(Integer listaPers) {
     this.listaPers = listaPers;
 }
 public String getMarcaPers() {
     return this.marcaPers;
 }
 
 public void setMarcaPers(String marcaPers) {
     this.marcaPers = marcaPers;
 }




}


